version: "3.8"

services:
  auth-service:
    build: ./services/auth
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: threadly_auth
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
